export interface ResultadoTest {
    id: number,
    id_resultadotest: number,
    id_alumno: number,
    nombre_alumno: string,
    nro_documento: number,
    edad: number,
    //formar palabras//
    fp_area_id: number,
    fp_item_id: number,
    fp_pobtenido: number,
    fp_pminimo: number,
    fp_pesperado: number,
    fp_indicador: string,
    fp_observacion: string,
    //discrimacion visual encontrar palabras//
    dva_area_id: number,
    dva_item_id: number,
    dva_pobtenido: number,
    dva_pminimo: number,
    dva_pesperado: number,
    dva_indicador: string,
    dva_observacion: string,
    //discrimacion palabras//
    dp_area_id: number,
    dp_item_id: number,
    dp_pobtenido: number,
    dp_pminimo: number,
    dp_pesperado: number,
    dp_indicador: string,
    dp_observacion: string,
    //encontrar letras en palabras//
    elp_area_id: number,
    elp_item_id: number,
    elp_pobtenido: number,
    elp_pminimo: number,
    elp_pesperado: number,
    elp_indicador: string,
    elp_observacion: string,
    //nombre correcto//
    nc_area_id: number,
    nc_item_id: number,
    nc_pobtenido: number,
    nc_pminimo: number,
    nc_pesperado: number,
    nc_indicador: string,
    nc_observacion: string,
    //letras desordenadas//
    ld_area_id: number,
    ld_item_id: number,
    ld_pobtenido: number,
    ld_pminimo: number,
    ld_pesperado: number,
    ld_indicador: string,
    ld_observacion: string,
    //discriminación visual contar palabras//
    dvb_area_id: number,
    dvb_item_id: number,
    dvb_pobtenido: number,
    dvb_pminimo: number,
    dvb_pesperado: number,
    dvb_indicador: string,
    dvb_observacion: string,
    //conciencia silábica//
    cs_area_id: number,
    cs_item_id: number,
    cs_pobtenido: number,
    cs_pminimo: number,
    cs_pesperado: number,
    cs_indicador: string,
    cs_observacion: string,
    //conciencia fonológica//
    cf_area_id: number,
    cf_item_id: number,
    cf_pobtenido: number,
    cf_pminimo: number,
    cf_pesperado: number,
    cf_indicador: string,
    cf_observacion: string,
    //derecha, izquierda//
    di_area_id: number,
    di_item_id: number,
    di_pobtenido: number,
    di_pminimo: number,
    di_pesperado: number,
    di_indicador: string,
    di_observacion: string,
    indicador: string,
    observacion: string
  }

  export interface ResultadoEjercicio {
    respuestaCorrectaEjercicio: string;
    respuestaHechaAlumno: string;
    acierto: boolean;
  }